### ISSUE TITLE
Any plans for improvements?

### ISSUE THREAD

**Issue by blinky3713** [purescript-contrib/purescript-machines#18]
This isn't as much of an issue, but I was recently using the kmett's [machines](https://hackage.haskell.org/package/machines-0.6.3) library in another project and noticed it had some benefits that I'm finding hard to implement with just the `MealyT` type. Noticeably, it seems like their `Await` constructor allows for a lot more flexibility. Are there any plans for expanding this library any directions? Interested in getting involved, but not sure what the maintainers think.

**Comment by jdegoes** [comment]
I’m open to make it a copy / port of the (much better) machines library.

**Comment by blinky3713** [comment]
great. I probably have time to start working on it these days, so I can volunteer to start working toward that. I'm also looking for an excuse to get into the details of that library so this works out well for me.
