### ISSUE TITLE
Rename Type Variables for MealyT

### ISSUE THREAD

**Issue by vladciobanu** [purescript-contrib/purescript-machines#41]
Rename `MealyT f s a` to `MealyT effect input output` or `MealyT eff i o` in order to make the type variables easier to understand.

**Additional context**
See the discussion in #38 for more context.

**Comment by thomashoneyman** [comment]
I would also be happy with `MealyT f i o`, as `f` is commonly used to represent "some Applicative `f`", and `i` + `o` is commonly interpreted as "input / output".

**Comment by paluh** [comment]
I have a hacking meeting tomorrow with @mhmdanas so I think that we can push this.
